---
- hosts: test_machine
  become: yes

  pre_tasks:
  - apt:
      name: python-docker
      update_cache: yes
    changed_when: False

  post_tasks:
  - apt:
      name: python-docker
      state: absent
      purge: yes
    changed_when: False

  roles:
  - role: '.'
    configs:
      gitlab:
        https: false
        upstreams:
          gitlab: "172.17.0.1:10080"
        server_name: git.flandigt.de
        locations:
        - location: /
          proxy_to: http://gitlab/
      harbor_ui:
        https: false
        upstreams:
          harbor_ui: "172.17.0.1:50080"
          harbor_registry: "172.17.0.1:55000"
        server_name: harbor.flandigt.de
        locations:
        - location: /
          proxy_to: http://harbor_ui/
        - location: /v1/
          returns: 404
        - location: /v2/
          proxy_to: http://harbor_registry/v2/
        - location: /service/
          proxy_to: http://harbor_ui/service/
        - location: /service/notifications
          returns: 404
