---
- name: create config directory
  file:
    path: "{{ nginx_conf_folder }}"
    state: directory
    owner: root
    group: root
    mode: 0750

- name: create rules directory
  file:
    path: "{{ nginx_rules_folder }}"
    state: directory
    owner: root
    group: root
    mode: 0750

- name: create certs directory
  file:
    path: "{{ nginx_certs_folder }}"
    state: directory
    owner: root
    group: root
    mode: 0750

- name: create ssl directory
  file:
    path: "{{ nginx_ssl_folder }}"
    state: directory
    owner: root
    group: root
    mode: 0750

- name: create www directory
  file:
    path: "{{ nginx_www_folder }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: create letsencrypt well-known directory
  file:
    path: "{{ nginx_letsencrypt_well_known_folder }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: create log directory
  file:
    path: "{{ nginx_log_folder }}"
    state: directory
    owner: root
    group: root
    mode: 0750

- name: create script directory
  file:
    path: "{{ nginx_script_folder }}"
    state: directory
    owner: root
    group: root
    mode: 0755
