---
- name: search for existing rule config files
  find:
    paths: "{{ nginx_rules_folder }}"
    patterns: '*.conf'
  register: existing_files

- name: determine intended site config files
  set_fact:
    intended_file_paths: >
      {{
      lookup('dict', nginx_rules)
      | selectattr('key', 'defined')
      | map(attribute='key')
      | map('regex_replace', '^(.*)$', '{{ nginx_rules_folder }}/\1.conf')
      | list
      }}

- name: determine site config files to be removed
  set_fact:
    files_to_remove_paths: >
      {{
      existing_files.files
      | selectattr('path', 'defined')
      | map(attribute='path')
      | reject('in', intended_file_paths)
      | list
      }}

- name: Remove unneeded site configs
  file:
    path: "{{ item }}"
    state: absent
  loop: "{{ files_to_remove_paths }}"
  notify: Reload nginx

- name: template rules config
  template:
    src: conf.d/rules.conf.j2
    dest: "{{ nginx_rules_folder }}/{{ item.key }}.conf"
  with_dict: "{{ nginx_rules }}"
  notify: Reload nginx
