---
- name: Search for existing rule config files
  find:
    paths: "{{ nginx_rules_folder }}"
    patterns: '*.conf'
  register: existing_files

- name: Determine intended rule config files
  set_fact:
    intended_file_paths: >
      {{
      lookup('dict', nginx_rules)
      | selectattr('key', 'defined')
      | map(attribute='key')
      | map('regex_replace', '^(.*)$', nginx_rules_folder + '/\1.conf')
      | list
      }}

- name: Determine rule config files to be removed
  set_fact:
    files_to_remove_paths: >
      {{
      existing_files.files
      | selectattr('path', 'defined')
      | map(attribute='path')
      | reject('in', intended_file_paths)
      | list
      }}

- name: Remove unneeded rule configs
  file:
    path: "{{ item }}"
    state: absent
  loop: "{{ files_to_remove_paths }}"
  notify: Reload nginx

- name: Template rules config
  include_tasks: create-rule.yml
  loop: "{{ nginx_rules | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
