---
- name: Check ticketkey file existence
  stat:
    path: "{{ticketkey_file_path}}"
  register: nginx_ticketkey_check

- name: Create renew ticketkey script
  template:
    src: renew_ticketkey.bash.j2
    dest: "{{ticketkey_renew_script}}"
    mode: 0755
  register: ticketkey_renew_script_creation

- name: Generate ticketkey file
  raw: "{{ticketkey_renew_script}}"
  when: ticketkey_enabled and (not nginx_ticketkey_check.stat.exists or ticketkey_renew_script_creation.changed)
