---
- name: template ssl rules
  template:
    src: rules/ssl_parameters.conf.j2
    dest: "{{ rules_folder }}/{{ ssl_parameters_file }}"
  notify: Reload nginx

- name: template reverse proxy rules
  template:
    src: rules/proxy_parameters.conf.j2
    dest: "{{ rules_folder }}/{{ proxy_parameters_file }}"
  notify: Reload nginx
