---
- include: check-parameters.yml

- name: Create systemd unit file
  template:
    src: nginx.systemd.j2
    dest: "/etc/systemd/system/{{ systemd_service_name }}.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - Enable nginx service
    - Restart nginx service

- name: pull image
  docker_image:
    name: "{{ image_name }}:{{ image_version }}"
    source: pull
  notify: Restart nginx service

- include: create_volumes.yml

- include: create-rules.yml

- include: create_dh_parameter.yml

- name: template upstream config
  template:
    src: conf.d/upstreams.conf.j2
    dest: "{{ conf_folder }}/upstreams.conf"
  notify: Reload nginx

- name: template site configs
  include: setup-site-configs.yml

- name: Create reloader service
  template:
    src: nginx.reload.systemd.j2
    dest: "/etc/systemd/system/{{ reload_service_name }}.service"
    owner: root
    group: root
    mode: 0644
  notify: Enable nginx reload service

- name: Setup logrotate config
  template:
    src: logrotate.j2
    dest: "{{ logrotate_config }}"

- include: setup-ticketkey.yml

- name: Start/Restart systemd services
  meta: flush_handlers

- name: Enable nginx service (if not started)
  systemd:
    name: "{{ service_name }}"
    enabled: true
    state: started
  when: not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )
