---
- include: check-parameters.yml

- name: Create systemd unit file
  template:
    src: nginx.systemd.j2
    dest: "/etc/systemd/system/{{ nginx_service_name }}.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - Enable nginx service
    - Restart nginx service

- name: pull image
  docker_image:
    name: "{{ nginx_image_name }}:{{ nginx_image_version }}"
    source: pull
  notify: Restart nginx service

- include: create_volumes.yml

- include: create-rules.yml

- include: create_dh_parameter.yml

- name: template nginx config
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_volume }}/nginx.conf"
  notify: Restart nginx service
  vars:
    config_dict: "{{ nginx_config }}"
  when: nginx_config is defined

- name: template site configs
  include: setup-site-configs.yml

- name: Create reloader service
  template:
    src: nginx.reload.systemd.j2
    dest: "/etc/systemd/system/{{ nginx_reload_service_name }}.service"
    owner: root
    group: root
    mode: 0644
  notify: Enable nginx reload service

- name: Setup logrotate config
  template:
    src: logrotate.j2
    dest: "{{ nginx_logrotate_config }}"

- include: setup-ticketkey.yml

- name: Start/Restart systemd services
  meta: flush_handlers

- name: Enable nginx service (if not started)
  systemd:
    name: "{{ nginx_service_name }}"
    enabled: true
    state: started
  when: not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )
