---
- name: pull image
  docker_image:
    name: "{{image_name}}:{{image_version}}"
    source: pull
  register: dockerimage

- name: Create systemd unit file
  template:
    src: nginx.systemd.j2
    dest: "/etc/systemd/system/{{systemd_service_name}}.service"
    owner: root
    group: root
    mode: 0644
  register: nginx_service

- name: Create reloader service
  template:
    src: nginx.reload.systemd.j2
    dest: "/etc/systemd/system/{{reload_service_name}}.service"
    owner: root
    group: root
    mode: 0644
  register: nginx_reload_service

- include: create_volumes.yml

- include: create-rules.yml

- name: template site config
  template:
    src: conf.d/site.conf.j2
    dest: "{{conf_folder}}/{{item.key}}.conf"
  with_dict: "{{ configs }}"
  register: site_config

- include: create_dh_parameter.yml

- name: Setup logrotate config
  template:
    src: logrotate.j2
    dest: "{{logrotate_config}}"

- include: setup-ticketkey.yml

- name: Reload systemd
  command: systemctl daemon-reload
  when: >
    nginx_service.changed
    or nginx_reload_service.changed
    or nginx_ticketkey_renew_service.changed
    or nginx_ticketkey_renew_timer.changed

- name: Generate new ticketkey
  service:
    name: "{{ticketkey_renew_service_name}}.service"
    state: started
  when: >
    ticketkey_enabled and not nginx_ticketkey_check.stat.exists

- name: Restart service
  service:
    name: nginx
    state: restarted
    enabled: yes
  when: dockerimage.changed or nginx_service.changed
  register: nginx_restart

- name: Start service (if necessary)
  service:
    name: nginx
    state: started
  register: nginx_start

- name: Reload nginx (needed for eventually config changes)
  service:
    name: "{{reload_service_name}}"
    state: started
  when: >
    not(nginx_restart.changed or nginx_start.changed)
    and (ssl_rules.changed or proxy_rules.changed
    or site_config.changed or dh_parameter.changed)
