---
- include: check-parameters.yml

- name: pull image
  docker_image:
    name: "{{ image_name }}:{{ image_version }}"
    source: pull
  notify: Restart nginx

- include: create_volumes.yml

- include: create-rules.yml

- include: create_dh_parameter.yml

- name: template upstream config
  template:
    src: conf.d/upstreams.conf.j2
    dest: "{{ conf_folder }}/upstreams.conf"
  notify: Reload nginx

- name: template site config
  template:
    src: conf.d/site.conf.j2
    dest: "{{ conf_folder }}/{{ item.key }}.conf"
  with_dict: "{{ configs }}"
  notify: Reload nginx

- name: Create systemd unit file
  template:
    src: nginx.systemd.j2
    dest: "/etc/systemd/system/{{ systemd_service_name }}.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - Reload systemd
    - Restart nginx

- name: Create reloader service
  template:
    src: nginx.reload.systemd.j2
    dest: "/etc/systemd/system/{{ reload_service_name }}.service"
    owner: root
    group: root
    mode: 0644
  notify: Reload systemd

- name: Setup logrotate config
  template:
    src: logrotate.j2
    dest: "{{ logrotate_config }}"

- include: setup-ticketkey.yml

- name: Enable nginx service
  service:
    name: "{{ service_name }}"
    enabled: true
  when: not (
      molecule_docker_environment is defined
      and molecule_docker_environment | bool
    )
  register: service_state
  changed_when: service_state.status.SubState != 'running'
  notify: Start nginx

- name: Flush handlers
  meta: flush_handlers
