---
- name: Search for existing site config files
  find:
    paths: "{{ nginx_conf_folder }}"
    patterns: '*.conf'
  register: existing_files

- name: Debug existing files
  debug:
    msg: "Existing file: {{ item }}"
  loop: "{{ existing_files.files }}"

- name: Determine intended site config files
  set_fact:
    intended_file_paths: >
      {{
      lookup('dict', nginx_configs)
      | selectattr('key', 'defined')
      | map(attribute='key')
      | map('regex_replace', '^(.*)$', nginx_conf_folder + '/\1.conf')
      | list
      + [nginx_conf_folder + '/nginx.conf']
      }}

- name: Debug intended files
  debug:
      msg: "Intended file: {{ item }}"
  loop: "{{ intended_file_paths }}"

- name: Determine site config files to be removed
  set_fact:
    files_to_remove_paths: >
      {{
      existing_files.files
      | selectattr('path', 'defined')
      | map(attribute='path')
      | reject('in', intended_file_paths)
      | list
      }}

- name: Debug files to remove
  debug:
    msg: "File to be removed: {{ item }}"
  loop: "{{ files_to_remove_paths }}"

- name: Remove unneeded site configs
  file:
    path: "{{ item }}"
    state: absent
  loop: "{{ files_to_remove_paths }}"
  notify: Reload nginx

- name: template site config
  include_tasks: setup-site-config.yml
  loop: "{{ nginx_configs | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
