---
- name: Check ticketkey file existence
  stat:
    path: "{{ ticketkey_file_path }}"
  register: nginx_ticketkey_check

- name: Create ticketkey renew service
  template:
    src: nginx-ticketkey-renew.systemd.j2
    dest: "/etc/systemd/system/{{ ticketkey_renew_service_name }}.service"
    owner: root
    group: root
    mode: 0644
  notify: Enable ticketkey renew service

- name: Create ticketkey renew timer
  template:
    src: nginx-ticketkey-renew.timer.systemd.j2
    dest: "/etc/systemd/system/{{ ticketkey_renew_service_name }}.timer"
    owner: root
    group: root
    mode: 0644
  notify:
    - Reload ticketkey renew service timer
