---
- name: Check ticketkey file existence
  stat:
    path: "{{ ticketkey_file_path }}"
  register: nginx_ticketkey_check

- name: Create ticketkey renew service
  template:
    src: nginx-ticketkey-renew.systemd.j2
    dest: "/etc/systemd/system/{{ ticketkey_renew_service_name }}.service"
    owner: root
    group: root
    mode: 0644
  notify: Reload systemd

- name: Setup ticketkey renew service
  systemd:
    name: "{{ ticketkey_renew_service_name }}.service"
    enabled: true

- name: Create ticketkey renew timer
  template:
    src: nginx-ticketkey-renew.timer.systemd.j2
    dest: "/etc/systemd/system/{{ ticketkey_renew_service_name }}.timer"
    owner: root
    group: root
    mode: 0644
  notify: Reload systemd

- name: Enable ticketkey renew service timer
  systemd:
    name: "{{ ticketkey_renew_service_name }}.timer"
    enabled: true
  when: ticketkey_enabled is defined
    and (ticketkey_enabled | bool)
  notify: Start ticketkey renew service timer

- name: Disable ticketkey renew service timer
  systemd:
    name: "{{ ticketkey_renew_service_name }}.timer"
    enabled: false
  when: not (
    ticketkey_enabled is defined
    and (ticketkey_enabled | bool)
    )
  notify: Stop ticketkey renew service timer
