---
- name: search for existing site config files
  find:
    paths: "{{ nginx_conf_folder }}"
    patterns: '*.conf'
  register: existing_files

- name: determine intended site config files
  set_fact:
    intended_file_paths: >
      {{
      lookup('dict', nginx_configs)
      | selectattr('key', 'defined')
      | map(attribute='key')
      | map('regex_replace', '^(.*)$', '{{ nginx_conf_folder }}/\1.conf')
      | list
      + ['{{ nginx_conf_folder }}/upstreams.conf']
      }}

- name: determine site config files to be removed
  set_fact:
    files_to_remove_paths: >
      {{
      existing_files.files
      | selectattr('path', 'defined')
      | map(attribute='path')
      | reject('in', intended_file_paths)
      | list
      }}

- name: Remove unneeded site configs
  file:
    path: "{{ item }}"
    state: absent
  loop: "{{ files_to_remove_paths }}"
  notify: Reload nginx

- name: template site config
  include: setup-site-config.yml
  with_dict: "{{ nginx_configs }}"
