---
- name: search for existing site config files
  find:
    paths: "{{ conf_folder }}"
    patterns: '*.conf'
  register: existing_files

- name: determine intended site config files
  set_fact:
    intended_file_paths: >
      {{
      lookup('dict', configs)
      | selectattr('key', 'defined')
      | map(attribute='key')
      | map('regex_replace', '^(.*)$', '{{ conf_folder }}/\1.conf')
      | list
      + ['{{ conf_folder }}/upstreams.conf']
      }}

- debug:
    var: intended_file_paths

- name: determine site config files to be removed
  set_fact:
    files_to_remove_paths: >
      {{
      existing_files.files
      | selectattr('path', 'defined')
      | map(attribute='path')
      | reject('in', intended_file_paths)
      | list
      }}

- name: Remove unneeded site configs
  file:
    path: "{{ item }}"
    state: absent
  loop: "{{ files_to_remove_paths }}"
  notify: Reload nginx

- name: template site config
  template:
    src: conf.d/site.conf.j2
    dest: "{{ conf_folder }}/{{ item.key }}.conf"
  with_dict: "{{ configs }}"
  notify: Reload nginx
