Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 443, host: 8443

  config.vm.network "private_network", ip: "192.168.33.26"

  config.vm.provider "virtualbox" do |v|
    v.name = "ansible_nginx"
  end
end
