---
- name: Enable ticketkey renew service
  systemd:
    name: "{{ nginx_ticketkey_renew_service_name }}.service"
    enabled: true
  when: not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )

- name: Reload ticketkey renew service timer
  systemd:
    name: "{{ nginx_ticketkey_renew_service_name }}.timer"
    enabled: "{{ nginx_ticketkey_enabled is defined
      and nginx_ticketkey_enabled | bool }}"
    state: "{{ 'started' if (
      nginx_ticketkey_enabled is defined
      and nginx_ticketkey_enabled | bool
      ) else 'stopped' }}"
  when: not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )

- name: Enable nginx service
  systemd:
    name: "{{ nginx_service_name }}"
    enabled: true
    daemon_reload: true
  when: not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )

- name: Restart nginx service
  systemd:
    name: "{{ nginx_service_name }}"
    state: restarted
    daemon_reload: true
  register: nginx_restart
  when: not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )

- name: Enable nginx reload service
  systemd:
    name: "{{ nginx_reload_service_name }}"
    enabled: true
    daemon_reload: true
  when: not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )

- name: Reload nginx
  systemd:
    name: "{{ nginx_reload_service_name }}"
    state: started
    daemon_reload: true
  when: not (
    nginx_restart is defined
    and nginx_restart.changed
    ) and not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )
