---
- name: Reload systemd
  systemd:
    daemon_reload: true
  when: not (
      molecule_docker_environment is defined
      and molecule_docker_environment | bool
    )

- name: Start nginx
  service:
    name: "{{ service_name }}"
    state: started
  register: nginx_start

- name: Start ticketkey renew service timer
  systemd:
    name: "{{ ticketkey_renew_service_name }}.timer"
    state: started

- name: Stop ticketkey renew service timer
  systemd:
    name: "{{ ticketkey_renew_service_name }}.timer"
    state: stopped

- name: Restart nginx
  service:
    name: "{{ service_name }}"
    state: restarted
  register: nginx_restart
  when: not (
      nginx_start is defined
      and nginx_start.changed
    ) and not (
      molecule_docker_environment is defined
      and molecule_docker_environment | bool
    )

- name: Reload nginx
  service:
    name: "{{ reload_service_name }}"
    state: started
  when: not (
      nginx_restart is defined
      and nginx_restart.changed
    ) and not (
      nginx_start is defined
      and nginx_start.changed
    ) and not (
      molecule_docker_environment is defined
      and molecule_docker_environment | bool
    )
