---
dependency:
  name: galaxy
  options:
    role-file: ./molecule/shared/requirements.yml
    force: true

driver:
  name: vagrant

platforms:
  - name: ansible-nginx-noble
    box: cloud-image/ubuntu-24.04
  - name: ansible-nginx-jammy
    box: cloud-image/ubuntu-22.04
  - name: ansible-nginx-focal
    box: cloud-image/ubuntu-20.04
  - name: ansible-nginx-bookworm
    box: cloud-image/debian-12
    groups:
      - debian
  - name: ansible-nginx-bullseye
    box: cloud-image/debian-11
    groups:
      - debian

provisioner:
  name: ansible
  playbooks:
    converge: ../shared/converge.yml
  inventory:
    group_vars:
      debian:
        ansible_python_interpreter: /usr/bin/python3
    host_vars:
      ansible-nginx-noble:
        nginx_ca_name: ansible-nginx-noble
      ansible-nginx-jammy:
        nginx_ca_name: ansible-nginx-jammy
      ansible-nginx-focal:
        nginx_ca_name: ansible-nginx-focal
      ansible-nginx-bookworm:
        nginx_ca_name: ansible-nginx-bookworm
      ansible-nginx-bullseye:
        nginx_ca_name: ansible-nginx-bullseye

verifier:
  name: ansible
