---
dependency:
  name: galaxy
  options:
    role-file: ./molecule/shared/requirements.yml

driver:
  name: vagrant
  provider:
    name: virtualbox

platforms:
  - name: ansible-nginx-xenial
    box: ubuntu/xenial64
    instance_raw_config_args:
      - 'vm.network "private_network", ip: "192.168.33.67"'
  - name: ansible-nginx-bionic
    box: ubuntu/bionic64
  - name: ansible-nginx-focal
    box: ubuntu/focal64
  - name: ansible-nginx-stretch
    box: debian/stretch64
    groups:
      - debian
  - name: ansible-nginx-buster
    box: debian/buster64
    groups:
      - debian

provisioner:
  name: ansible
  playbooks:
    converge: ../shared/converge.yml
  inventory:
    group_vars:
      debian:
        ansible_python_interpreter: /usr/bin/python3
    host_vars:
      ansible-nginx-stretch:
        nginx_ca_name: ansible-nginx-stretch
      ansible-nginx-buster:
        nginx_ca_name: ansible-nginx-buster
      ansible-nginx-focal:
        nginx_ca_name: ansible-nginx-focal
      ansible-nginx-bionic:
        nginx_ca_name: ansible-nginx-bionic
      ansible-nginx-xenial:
        nginx_ca_name: ansible-nginx-xenial

verifier:
  name: ansible
