---
dependency:
  name: galaxy
  options:
    role-file: ./molecule/shared/requirements.yml
    force: true

lint: |
  set -e
  yamllint . --strict
  ansible-lint

driver:
  name: docker

platforms:
  - name: docker-noble
    image: docker.io/borisskert/python3:noble
    pull: true
    pre_build_image: true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    groups:
      - docker
#  - name: docker-jammy
#    image: docker.io/borisskert/python3:jammy
#    pull: true
#    pre_build_image: true
#    volumes:
#      - '/var/run/docker.sock:/var/run/docker.sock'
#    groups:
#      - docker
#  - name: docker-focal
#    image: docker.io/borisskert/python3:focal
#    pull: true
#    pre_build_image: true
#    volumes:
#      - '/var/run/docker.sock:/var/run/docker.sock'
#    groups:
#      - docker
#
#  - name: docker-bookworm
#    image: docker.io/borisskert/python3:bookworm
#    pull: true
#    pre_build_image: true
#    volumes:
#      - '/var/run/docker.sock:/var/run/docker.sock'
#    groups:
#      - docker
#      - debian
#
#  - name: docker-bullseye
#    image: docker.io/borisskert/python3:bullseye
#    pull: true
#    pre_build_image: true
#    volumes:
#      - '/var/run/docker.sock:/var/run/docker.sock'
#    groups:
#      - docker
#      - debian

provisioner:
  name: ansible
  playbooks:
    converge: ../shared/converge.yml
  inventory:
    group_vars:
      docker:
        molecule_docker_environment: true
      debian:
        ansible_python_interpreter: /usr/bin/python3
    host_vars:
      ansible-nginx-noble:
        nginx_ca_name: ansible-nginx-noble
      ansible-nginx-jammy:
        nginx_ca_name: ansible-nginx-jammy
      ansible-nginx-focal:
        nginx_ca_name: ansible-nginx-focal
      ansible-nginx-bookworm:
        nginx_ca_name: ansible-nginx-bookworm
      ansible-nginx-bullseye:
        nginx_ca_name: ansible-nginx-bullseye

verifier:
  name: ansible
