---
dependency:
  name: galaxy
  options:
    role-file: ./molecule/shared/requirements.yml

lint: |
  set -e
  yamllint . --strict
  ansible-lint

driver:
  name: docker

platforms:
  - name: ansible-nginx-focal
    image: docker.io/borisskert/python3:focal
    pull: true
    pre_build_image: true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    groups:
      - docker
  - name: ansible-nginx-bionic
    image: docker.io/borisskert/python3:bionic
    pull: true
    pre_build_image: true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    groups:
      - docker
  - name: ansible-nginx-xenial
    image: docker.io/borisskert/python3:xenial
    pull: true
    pre_build_image: true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    groups:
      - docker
  - name: ansible-nginx-buster
    image: docker.io/borisskert/python3:buster
    pull: true
    pre_build_image: true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    groups:
      - docker
      - debian
  - name: ansible-nginx-stretch
    image: docker.io/borisskert/python3:stretch
    pull: true
    pre_build_image: true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    groups:
      - docker
      - debian

provisioner:
  name: ansible
  playbooks:
    converge: ../shared/converge.yml
  inventory:
    group_vars:
      docker:
        molecule_docker_environment: true
      debian:
        ansible_python_interpreter: /usr/bin/python3
    host_vars:
      ansible-nginx-stretch:
        nginx_ca_name: ansible-nginx-stretch
      ansible-nginx-buster:
        nginx_ca_name: ansible-nginx-buster
      ansible-nginx-focal:
        nginx_ca_name: ansible-nginx-focal
      ansible-nginx-bionic:
        nginx_ca_name: ansible-nginx-bionic
      ansible-nginx-xenial:
        nginx_ca_name: ansible-nginx-xenial

verifier:
  name: ansible
