---
- name: Prepare
  hosts: all
  become: true

  post_tasks:
    - name: Perform prepare
      include: ../shared/prepare.yml

  roles:
    - role: install-docker
      storage_driver: overlay2
      cleanup_enabled: false
      install_pip_docker: true
