---
- name: Converge
  hosts: all
  become: true

  roles:
    - role: ansible-nginx
      volume: /srv/nginx
      http_port: 8080
      https_port: 8443
      clear_dh_parameter: false
      dh_parameter_bits: 1024
      ticketkey_enabled: true
      upstreams:
        apache: 172.17.0.1:10080
      configs:
        apache:
          https: false
          server_name: my.myserver.org
          locations:
            '/':
              proxy_pass: http://apache/
              include: /etc/nginx/rules/proxy_parameters.conf
            '~ /.well-known':
              root: /var/www/html
              allow: all
