---
- name: Converge
  hosts: all
  become: true

  roles:
    - role: ansible-nginx
      volume: /srv/nginx
      http_port: 8080
      https_port: 8443
      clear_dh_parameter: false
      dh_parameter_bits: 1024
      ticketkey_enabled: true
      upstreams:
        apache: 172.17.0.1:10080
      configs:
        apache:
          servers:
            - options:
                listen:
                  - '80'
                  - '[::]:80'
                server_name: my.http.server
              locations:
                '/':
                  proxy_pass: http://apache/
                  include: ./rules/proxy_parameters.conf
                '~ /.well-known':
                  root: /var/www/html
                  allow: all
        https:
          servers:
            - options:
                listen:
                  - '80'
                  - '[::]:80'
                server_name: my.https.server
                return: 301 https://$server_name$request_uri
            - options:
                listen:
                  - '443 ssl http2'
                  - '[::]:443 ssl http2'
                server_name: my.https.server
                ssl_certificate: ./certs/live/my.https.server/fullchain.pem
                ssl_certificate_key: ./certs/live/my.https.server/privkey.pem
                ssl_trusted_certificate: ./certs/live/my.https.server/chain.pem
                include: ./rules/ssl_parameters.conf
              locations:
                '/':
                  proxy_pass: http://apache/
                  include: ./rules/proxy_parameters.conf
                '~ /.well-known':
                  root: /var/www/html
                  allow: all
