---
- name: Create site directory
  file:
    path: /srv/nginx/conf.d
    state: directory

- name: Create dummy site config
  copy:
    dest: /srv/nginx/conf.d/dummy.conf
    content: |
      server {
        listen 80;
        listen [::]:80;
        server_name my.dummy.site;
        location ~ /.well-known {
          root /var/www/html;
          allow all;
        }
      }

- name: Create rules directory
  file:
    path: /srv/nginx/rules
    state: directory

- name: Create dummy rules config
  copy:
    dest: /srv/nginx/rules/dummy.conf
    content: |
      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_cookie_path / \"/; secure\";
      proxy_buffering off;
      proxy_request_buffering off;
