---
name: Run tests

'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  molecule_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"

      - name: lint and test (scenario 'default') with molecule
        uses: borisskert/molecule-action@v20.07.21
        with:
          arguments: test

      - name: lint and test (scenario 'without-nginx-conf') with molecule
        uses: borisskert/molecule-action@v20.07.21
        with:
          arguments: test -s without-nginx-conf
